src/TheDahllHaus/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheDahllHaus.Models
{
    [Table("Categories")]
    public class Category
    {
        public Category()
        {
            this.Items = new HashSet<Item>();
        }

        [Key]
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}

src/TheDahllHaus/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheDahllHaus.Models;
using Microsoft.EntityFrameworkCore;

namespace TheDahllHaus.Controllers
{
    public class CategoriesController : Controller
    {
        private TheDahllHausDbContext db = new TheDahllHausDbContext();
        public IActionResult Index()
        {
            return View(db.Categories.ToList());
        }
        public IActionResult Details(int Id)
        {
            var thisCategory = db.Categories.Include(categories => categories.Items).FirstOrDefault(categories => categories.CategoryId == Id);

            //ICollection<Experience> thisCategoryItems = thisCategory.Items;
            return View(thisCategory);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            db.Categories.Add(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Edit
        public IActionResult Edit(int id)
        {
            var thisCategory = db.Categories.FirstOrDefault(categories => categories.CategoryId == id);
            return View(thisCategory);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            db.Entry(category).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Delete
        public IActionResult Delete(int id)
        {
            var thisCategory = db.Categories.FirstOrDefault(items => items.CategoryId == id);
            return View(thisCategory);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisCategory = db.Categories.FirstOrDefault(items => items.CategoryId == id);
            db.Categories.Remove(thisCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TheDahllHaus/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheDahllHaus.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheDahllHaus.Controllers
{
    public class ItemsController : Controller
    {
        private TheDahllHausDbContext db = new TheDahllHausDbContext();

        public IActionResult Index()
        {
            return View(db.Items.Include(items => items.Category).ToList());
        }

        //Details
        public IActionResult Details(int id)
        {
            var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }
        //Create 
        public IActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Item item)
        {
            db.Items.Add(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Edit
        public IActionResult Edit(int id)
        {
            var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View(thisItem);
        }
        [HttpPost]
        public IActionResult Edit(Item item)
        {
            db.Entry(item).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Delete
        public ActionResult Delete(int id)
        {
            var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
            db.Items.Remove(thisItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TheDahllHaus/Views/Categories/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/TheDahllHaus/Views/Categories/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/TheDahllHaus/Views/Categories/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/TheDahllHaus/Views/Categories/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/TheDahllHaus/Views/Categories/Index.cshtml
<link href="https://fonts.googleapis.com/css?family=Amatic+SC|Satisfy|Archivo+Narrow" rel="stylesheet">

@{
    ViewData["Title"] = "The Dahll Haus Shop Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<TheDahllHaus.Models.Category>


<div class="mui-container-fluid">
    <h1 class="headingText" align="center">Welcome to the Shop!</h1>
    <div class="mui-divider"></div>
    <br />
    <div class="mui-container-fluid">
        <div align="center">
            <img src="~/images/creations/bunny1.jpg" width="300" />
            <img src="~/images/creations/wig-amy.jpg" width="300" />
            <img src="~/images/creations/skull3.jpg" width="300" />
        </div>
        <div class="mui-row">
            @foreach (var listCategory in Model)
            {
                <div class="mui-col-md-4 mui--divider-right">
                    <h2 style="font-family: 'Satisfy', cursive;">@Html.DisplayFor(modelCategory => listCategory.Name)</h2>
                    <button class="mui-btn mui-btn--dark mui-btn--small">@Html.ActionLink("See Items", "Index", "Items")</button>
                    <div class="mui-divider"></div>
                </div>
            }
        </div>
    </div>
</div>