src/TheDahllHaus/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheDahllHaus.Models;
using Microsoft.EntityFrameworkCore;

namespace TheDahllHaus.Controllers
{
    public class CategoriesController : Controller
    {
        private TheDahllHausDbContext db = new TheDahllHausDbContext();
        public IActionResult Index()
        {
            return View(db.Categories.ToList());
        }
        public IActionResult Details(int Id)
        {
            var thisCategory = db.Categories.Include(categories => categories.Items).FirstOrDefault(categories => categories.CategoryId == Id);

            //ICollection<Experience> thisCategoryItems = thisCategory.Items;
            return View(thisCategory);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            db.Categories.Add(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Edit
        public IActionResult Edit(int id)
        {
            var thisCategory = db.Categories.FirstOrDefault(categories => categories.CategoryId == id);
            return View(thisCategory);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            db.Entry(category).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Delete
        public IActionResult Delete(int id)
        {
            var thisCategory = db.Categories.FirstOrDefault(items => items.CategoryId == id);
            return View(thisCategory);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisCategory = db.Categories.FirstOrDefault(items => items.CategoryId == id);
            db.Categories.Remove(thisCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TheDahllHaus/Controllers/MUAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TheDahllHaus.Controllers
{
    public class MUAController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/TheDahllHaus/Controllers/RepairController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheDahllHaus.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;



namespace TheDahllHaus.Controllers
{
    public class RepairController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/TheDahllHaus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//cdn.muicss.com/mui-0.9.24/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Satisfy|Archivo|Archivo+Narrow" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet" />

    <script src="//cdn.muicss.com/mui-0.9.24/js/mui.min.js"></script>
    <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>

    <script src="//cdn.muicss.com/mui-0.9.24/extra/mui-combined.js"></script>
    <script src="//cdn.muicss.com/mui-0.9.24/extra/mui-combined.min.js"></script>
    <script src="~/js/scripts.js"></script>

    <script src="https://use.fontawesome.com/c3a95916f1.js"></script>


    <title>@ViewBag.Title</title>
</head>

<body>
    <div id="sidedrawer">
        <div id="sidedrawer-brand">
            <img src="~/images/kateslogos/thedahllhouse_logo_white.png" height="40" style="padding-top:10px;" />
        </div>
        <div class="mui-divider"></div>
        <ul>
            <li>
                <strong style="color:white;">@Html.ActionLink("THE DAHLL HAUS", "Index", "Home")</strong>
                <ul>
                    <li class="list-group-item">@Html.ActionLink("Meet the Artist", "About", "Home", null, new { @id ="parentLink" })</li>
                    <li class="list-group-item">@Html.ActionLink("Ask for a quote", "Contact", "Home")</li>
                    <li class="list-group-item">@Html.ActionLink("Dahll Haus Love Notes", "Reviews", "Home")</li>
                </ul>
            </li>
            <li>
                <strong style="color:white;">@Html.ActionLink("THE DAHLL HAUS SHOP", "Index", "Categories")</strong>
            </li>
            <li>
                <strong style="color:white;">@Html.ActionLink("REPAIRS AND ALTERATION SERVICES", "Index", "Repair")</strong>
            </li>
            <li>
                <strong style="color:white;">@Html.ActionLink("MUA PORTFOLIO", "Index", "MUA")</strong>
          </li>
        </ul>
    </div>
    <header id="header">
        <div class="mui-appbar mui--appbar-height">
            <table width="100%" class="navbar">
                <tr style="vertical-align:middle;">
                    <td class="mui--appbar-height"><a class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm js-hide-sidedrawer">☰</a>
                    <a class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block js-show-sidedrawer">☰</a>
                    </td>
                    <td class="mui--appbar-height" align="center">
                        <span class="mui-image--fix" style="padding-left:120px;">
                            <img src="~/images/kateslogos/thedahllhouse_logo_white.png" height="50" style="padding-top:10px;" />
                        </span>
                    </td>
                    <td class="mui--appbar-height" align="right">
                        <a href="https://www.facebook.com/TheDahllHaus"><i class="fa fa-facebook-official fa-2x" aria-hidden="true">&nbsp&nbsp&nbsp</i></a><a href="https://www.instagram.com/thedahllhaus"><i class="fa fa-instagram fa-2x" aria-hidden="true">&nbsp&nbsp&nbsp</i></a><a href="https://www.etsy.com/shop/TheDahllHaus"><i class="fa fa-etsy fa-2x" aria-hidden="true"></i></a>
                    </td>
                </tr>
            </table>
        </div>
    </header>
    <div id="content-wrapper">
        <div class="mui--appbar-height"></div>
        <div class="mui-container-fluid">
            @RenderBody()
        </div>
    </div>
    <footer id="footer">
        <div class="mui-container-fluid">
            <br>
            <p class="footText">Design by Amatorah Design | The Dahll Haus <i class="fa fa-copyright fa-fw" aria-hidden="true"></i>2017</p>
        </div>
    </footer>
</body>
</html>